### ISSUE TITLE
Crash with a ruby trace-back: Undefined method `form' 

### ISSUE THREAD

**Issue by tikums** [0xsauby/yasuo#18]
I am encountering a crash with trace-back output when running Yasuo v2.0 with the following flags:

```
# ruby /opt/yasuo/yasuo.rb --brute all --threads 4 --path-signatures /opt/yasuo/signatures.yaml -f /tmp/web_scan.sh-YMgujg.xml
[...]
Yasuo found Vivotek Mega-Pixel Network Camera at http://192.168.4.161:80/setup/system/system.html. May require form based auth
I, [2015-07-09T01:12:57.208220 #7856]  INFO -- : Double-checking if the application implements a login page and initiating login bruteforce, hold on tight...
/opt/yasuo/formloginbrute.rb:33:in `brute_by_force': undefined method `form' for #<Mechanize::File:0x9a06f50> (NoMethodError)
        from /opt/yasuo/yasuo.rb:322:in `block (2 levels) in find_vulnerable_applications'
        from /opt/yasuo/yasuo.rb:286:in `each'
        from /opt/yasuo/yasuo.rb:286:in `each_with_index'
        from /opt/yasuo/yasuo.rb:286:in `block in find_vulnerable_applications'
        from /opt/yasuo/yasuo.rb:280:in `each_key'
        from /opt/yasuo/yasuo.rb:280:in `find_vulnerable_applications'
        from /opt/yasuo/yasuo.rb:196:in `block (2 levels) in process_nmap_scan'
```

**Comment by 0xsauby** [comment]
Hi, are you using the latest version of Yasuo? Also, could you mask the IP addresses and send me the log file it created.

**Comment by tikums** [comment]
Hi @0xsauby, thank you for a very useful tool! Yes, I'm using a current version:

```
# pwd
/opt/yasuo
# git pull
Already up-to-date.
```

This is the relevant part from the output file ``yasuo_output_20150710101028UTC.log``:

```
# tail yasuo_output_20150710101028UTC.log
I, [2015-07-10T13:19:44.982729 #22317]  INFO -- : Testing ----> [Vivotek Mega-Pixel Network Camera] http://192.168.248.136:80/media/media_settings.html
I, [2015-07-10T13:19:44.983920 #22317]  INFO -- : Testing ----> [Vivotek Mega-Pixel Network Camera] http://192.168.4.14:2301/setup/system/system.html
I, [2015-07-10T13:19:44.986041 #22317]  INFO -- : <<<Primary path {http://192.168.4.14:2301/setup/system/system.html} was not found, looking for secondary path>>>
I, [2015-07-10T13:19:44.986072 #22317]  INFO -- : Testing ----> [Vivotek Mega-Pixel Network Camera] http://192.168.4.14:2301/media/media_settings.html
I, [2015-07-10T13:19:44.988026 #22317]  INFO -- : Testing ----> [Vivotek Mega-Pixel Network Camera] http://192.168.124.101:80/setup/system/system.html
I, [2015-07-10T13:19:44.991451 #22317]  INFO -- : <<<Primary path {http://192.168.124.101:80/setup/system/system.html} was not found, looking for secondary path>>>
I, [2015-07-10T13:19:44.991486 #22317]  INFO -- : Testing ----> [Vivotek Mega-Pixel Network Camera] http://192.168.124.101:80/media/media_settings.html
I, [2015-07-10T13:19:44.994405 #22317]  INFO -- : Testing ----> [Vivotek Mega-Pixel Network Camera] http://192.168.4.160:80/setup/system/system.html
I, [2015-07-10T13:19:45.001599 #22317]  INFO -- : Yasuo found Vivotek Mega-Pixel Network Camera at http://192.168.4.160:80/setup/system/system.html. May require form based auth
I, [2015-07-10T13:19:45.001872 #22317]  INFO -- : Double-checking if the application implements a login page and initiating login bruteforce, hold on tight...
```

As can be seen, it simply did not finish. Please let me know if you'd like to know more.

**Comment by 0xsauby** [comment]
And I believe it crashed right after this? Is it the recurring behavior? Also, I am assuming that you have following files in the same directory:
formloginbrute.rb
signatures.yaml	
yasuo.rb
pass.txt
signatures_top.yaml		
users.txt

**Comment by tikums** [comment]
Yes, it seems to crash right after attempting brute-force on this host.

I confirm that all the files listed are present in Yasuo's working directory.

**Comment by 0xsauby** [comment]
I am trying to reproduce the error. Will post an update soon.

**Comment by 0xsauby** [comment]
I am unable to reproduce this error. Can you please do a fresh pull and run it again. Also make sure you have Mechanize gem installed.

**Comment by shellster** [comment]
I am also having the exact same problem.

**Comment by 0xsauby** [comment]
Can you provide some more info like which app path is it crashing on?

**Comment by shellster** [comment]
I'll see if I can look through my log and provide you with some sanitized information.  I ended up reverting to a version that was a couple of git check-ins back, and that fixed the problem.

**Comment by 0xsauby** [comment]
In that case, can you please verify if the app path signature that Yasuo crashed on, exists in the older version that worked.

**Comment by 0xsauby** [comment]
This should be fixed in the latest version.
