### ISSUE TITLE
undefined method `include?'

### ISSUE THREAD

**Issue by jrmdev** [0xsauby/yasuo#28]
Hi,

When I run yasuo providing a .xml nmap scan file, I receive the following error after some time aand then the program terminates.

```
[+] Yasuo found Apache Tomcat at http://(redacted):8080/manager/html. Requires HTTP basic auth
yasuo.rb:383:in `block (2 levels) in find_vulnerable_applications': undefined method `include?' for nil:NilClass (NoMethodError)
	from yasuo.rb:364:in `each'
	from yasuo.rb:364:in `each_with_index'
	from yasuo.rb:364:in `block in find_vulnerable_applications'
	from yasuo.rb:357:in `each_key'
	from yasuo.rb:357:in `find_vulnerable_applications'
	from yasuo.rb:270:in `block (2 levels) in process_nmap_scan'

```

**Comment by 0xsauby** [comment]
Hey,
Thanks for reporting the issue. I think I know what the problem is. The location header returns NIL, which I am not handling in the code. Will fix it in a few hours and update here.

**Comment by 0xsauby** [comment]
This issue has been fixed now.
